version: "3.7"
services:
  trino:
    image: trinodb/trino:351
    volumes:
      - "./trino-config-docker/etc:/etc/trino"
      - "./trino-config-docker/plugin/trino-auth:/usr/lib/trino/plugin/trino-auth"
      - "./trino-config-docker/plugin/trino-events:/usr/lib/trino/plugin/trino-events"
    ports:
      - "8080:8080"
